version: '2'
services:
  web0:
    build:
      context: potato
    restart: unless-stopped
    expose: ["8080", "8081"]
    command: ["--potato"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  web1:
    build:
      context: potato
    restart: unless-stopped
    expose: ["8080"]
    command: ["--potato"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  web2:
    build:
      context: potato
    restart: unless-stopped
    expose: ["8080"]
    command: ["--potato"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  state-server:
    build:
      context: potato
    restart: unless-stopped
    command: ["--state-server"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  content-processor:
    build:
      context: potato
    restart: unless-stopped
    command: ["--content-processor"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  index-manager:
    build:
      context: potato
    restart: unless-stopped
    command: ["--index"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  email-updates:
    build:
      context: potato
    restart: unless-stopped
    command: ["--email-updates"]
    links:
      - couchdb
      - rabbitmq
      - memcached
      - solr
    volumes:
      - files:/var/potato/files

  couchdb:
    image: klaemo/couchdb:latest

  rabbitmq:
    image: rabbitmq:3.6.3

  memcached:
    image: memcached:latest

  solr:
    build:
      context: solr

  haproxy:
    build:
      context: haproxy
    ports: ["80:80"]
    expose: ["80"]
    links:
      - web0
      - web1
      - web2

volumes:
  files: {}
