version: '2'
services:
  couchdb:
    image: lokedhs/couchdb:latest
    ports: ["5984:5984"]
    expose: ["5984"]
    volumes:
      - couchdb-volume:/opt/couchdb/data

  rabbitmq:
    build:
      context: ../rabbitmq
    ports: ["5672:5672", "15672:15672"]
    expose: ["5672", "15672"]

  memcached:
    image: memcached:latest
    ports: ["11211:11211"]
    expose: ["11211"]

  solr:
    build:
      context: ../solr
    ports: ["8983:8983"]
    expose: ["8983"]

volumes:
  files: {}
  couchdb-volume:
